config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories

    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase}
    validates :username, presence: true, length: { minimum:3, maximum:25 }, uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, uniqueness: true, presence: true, length: { maximum:105 }, uniqueness: {case_sensitive: false}, 
                format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    add_flash_types :danger, :success, :notice, :info

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform this action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
      @article = Article.new
  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        flash[:notice] = "Article was successfuly created"
        redirect_to articles_path
      else
        render 'new'
      end
  end

  def show

  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to user_path(user)
    else
        flash.now[:danger] = "There was something wrong with your information "
        render 'new'
    end
end

def destroy
    session[:user_id] = nil
    flash[:success] = "You have been successfully logged out"
    redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Account was successfully updated"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles were deleted"
        redirect_to users_path
    end

    def set_user
        @user = User.find(params[:id])
    end 

    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to Alpha-Blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin can perform this action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def bootstrap_class_for(flash_type)
        case flash_type
        when "success"
            "alert-success"
        when "error"
            "alert-danger"
        when "alert"
            "alert-warning"
        when "notice"
            "alert-info"
        else
            flash_type.to_s
        end
    end
    
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class:"rounded-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row" style="display: block;
    width: 50%;
    margin-left: auto;
    margin-right: auto;">
    <div class="col-xs-8 offset-xs-2">
      <div class="card card-lg" style="box-shadow: 5px 5px 5px #888888;
      border-radius: 10px">
        <div class="article-title">
        <%= link_to article.title, article_path(article) %></td>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class = "article-meta-details" style="padding: 10px">
            <small>Created by: <%= article.user.username if article.user%>,
              <%= time_ago_in_words(article.created_at)%> ago,
              last updated: <%= time_ago_in_words(article.updated_at)%> ago
            </small>
            <% if article.categories.any? %>
              <div class="center mr-2"> <%= render article.categories %></div>
            <% end %>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions"
               style="display: inline;
                 width: 60%;
                 margin-left: auto;
                 margin-right: auto;" >

            <%= link_to "Back to articles list", articles_path, class: "btn btn-xs btn-success" %> 
            <%= link_to "Delete this article", articles_path(article), method: :delete ,  
                data: {confirm: "Are you sure?"},
                class: "btn btn-xs btn-danger" %>
          </div>
          <br>
        <% end %>
      </div>
      <br>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div class="row" style="display: block;
    width: 50%;
    margin-left: auto;
    margin-right: auto;">
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h4>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class='row' style="display: block;
  width: 50%;
  margin-left: auto;
  margin-right: auto;">
  <div class='md-8' style="align: center">
    <%= form_for @article do |f| %>
      <div class="form-group" style="align: center">
        <div class="control-label sm-2">
          <%= f.label :title %>
        </div>
        <div class="sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
        <div class="form-group" >
          <div class="control-label sm-2">
            <%= f.label :description %>
          </div>
          <div class="sm-8">
            <%= f.text_area :description, class:"form-control", placeholder: "Body of article" %>
          </div>
        </div>

      <div class="form-group">
        <div class="control-label sm-2">
          <%= f.label :categories %>
        </div>
        <div class="sm-8">
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                  { prompt: "Make your selection"}, { multiple: true, class: "custom-select"}) %>
        </div>
      </div>
      <br>
        <div class="form-group" style="display: block;
          width: 50%;
          margin-left: auto;
          margin-right: auto;">
          <div class="sm-10 offset-2">
            <%= f.submit%>
            <br>
            <br>
            <%= link_to "Back to articles list", articles_path %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit articles</h1>


<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<br>
<%= render 'article', obj: @articles %>
<div class="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<br>
<h1 class="text-center mt-4">Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"> Title: <%= @article.title %></h2>
<br>

<div class="card xs-8 offset-xs-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class = "col-md-4 offset-md-4" style="padding: 10px">
          <li>Created by:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <% if @article.categories.any? %>
            <div> <%= render @article.categories %></div>
          <% end %>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>

  <h4 class="center"><strong> Description: </strong> </h4>

  <h4 align="center"> <%= @article.description %></h4>
  
  <div class="article-actions"
       style="display: inline;
         width: 60%;
         margin-left: 30%;
         margin-right: 70%;" >
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Delete this article", articles_path(@article), method: :delete ,  
      data: {confirm: "Are you sure?"},
      class: "btn btn-xs btn-danger" %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary"%>
    <%= link_to "Back to articles list", articles_path, class: "btn btn-xs btn-success" %>
      <br>
  <% end %>
  </div>
  <br>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-primary mr-1"%>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group" align ="center">
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "Input category name", autofocus: true %>
    </div>
  </div>
  <br>
  <div class="form-group" align ="center">
    <div class="col-sm-6">
      <%= f.submit "Create" %>
    </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit <% @category.name %> category</h1>
<br>
<%= render 'form' %>

<%= link_to "Back to articles list", articles_path %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<br>
<div align="center">
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 offset-md-4">
                    <li class="article-title">
                    <%= link_to "#{category.name}", category_path(category) %>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 style="align: center">Create new category</h1>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
    <div class="control-label sm-2">
        <%= f.label :name %><br>
    </div>
    <div class="sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Input category name", autofocus: true %>
    </div>
    </div> 
    <div class="form-group">
        <div class="sm-10 offset-2">
        <%= f.submit "Create" %>
        </div>
    </div>
    
<% end %>

<%= link_to "Back to articles list", articles_path %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-xs btn-primary" %>
  </div>
<% end %>
<br>

<h4 align="center"><%= @category.name %> articles </h4>

  <%= render 'articles/article', obj: @articles %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class = "footer">
        <small>
        Copyright &copy;
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= name %>%'>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark " style="box-shadow: 0px 5px 5px #888888;">
  <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <ul class="navbar-nav mr-auto">
            <li style="padding-left: 10px; padding-top: 5px"><%= link_to "Articles", articles_path, id: "first_item" %></li>
            <li style="padding-left: 10px; padding-top: 5px"><%= link_to "Categories", categories_path %></li>
            <li style="padding-left: 10px; padding-top: 5px"><%= link_to "Users", users_path %></li>

          </ul>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "Admin" if current_user.admin? %>
            </a>
            <div class="dropdown-menu" style="padding-left: 10px" aria-labelledby="navbarDropdown">
            <a class="dropdown-item"><%= link_to "Edit your profile", edit_user_path(current_user) %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item"><%= link_to "New Article", new_article_path %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item"><%= link_to "View your profile", user_path(current_user) %></a>
              <% if current_user.admin? %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item"><%= link_to "New Category", new_category_path %></a>
                <% end %>
            </div>
          </li>
          </ul>

          </ul>
          <p style="float: right; padding-top: 5px"><%= link_to 'Log Out', logout_path, method: :delete  %></p>
    <% else %>
      <li style="padding-left: 10px"><%= link_to 'Log in', login_path %></li>
      <li style="padding-left: 10px"><%= link_to 'Sign Up', signup_path %></li>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
        body{
            background-color: #eaeaea;
        }
    </style>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %> 
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}
.menu {
  float: middle;
  width: 100%;
}
.menuitem {
  padding: 8px;
  margin-top: 7px;
  border-bottom: 1px solid #f1f1f1;
}
.main {
  float: left;
  width: 60%;
  padding: 0 20px;
  overflow: hidden;
}
.right {
  background-color: lightblue;
  float: left;
  width: 20%;
  padding: 10px 15px;
  margin-top: 7px;
}

@media only screen and (max-width:800px) {
  /* For tablets: */
  .main {
    width: 80%;
    padding: 0;
  }
  .right {
    width: 100%;
  }
}
@media only screen and (max-width:500px) {
  /* For mobile phones: */
  .menu, .main, .right {
    width: 100%;
  }
}
</style>
</head>
<body style="font-family:Verdana;">

<div style="background-color:#f1f1f1;padding:15px;">
  <h1>Blogg Name by Syrbu</h1>
  <!--<h3>Resize the browser window</h3>-->
</div>

<div style="overflow:auto;">
    <div class="menu">
    <div class="menuitem"><%= link_to 'Home', root_path %>
</div>
    <!--<div class="menuitem">Transport</div>
    <div class="menuitem">History</div>
    <div class="menuitem">Gallery</div>-->
  </div>

  <div class="main">
    <h2>The Blogg about page</h2>
    <p>This is my blog guys</p>
    <img src="<!--Macintosh HD/Users/alfred2/Desktop/ruby/alpha_blog/app/views/pages/-->blog_home.jpeg" alt="me" style="width:100%"/>
  </div>

  <div class="right">
    <h2>What?</h2>
    <p>Syrbu loves you cuz he likes RoR</p>
    <h2>Where?</h2>
    <p>On Rails</p>
    <h2>Price?</h2>
    <p>Rails are free!</p>
  </div>
</div>


<!--<div style="background-color:#f1f1f1;text-align:center;padding:10px;margin-top:7px;font-size:12px;"> This web page is a part of a demonstration of fluid web design made by w3schools.com. Resize the browser window to see the content respond to the resizing.</div>-->

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>

</style>
</head>
<body style="font-family:Verdana;">
<br>
<div class="center jumbotron">
  <h1 style="padding-bottom: 20px">AlphaBlog</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>
</body>
</html>

app/views/users/_form.html.erb
<div class='row'>
<div class='md-8'>
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label sm-2">
        <%= f.label :username %><br>
      </div>
      <div class="sm-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Input username", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label sm-2">
        <%= f.label :email %>
      </div>
      <div class="sm-8">
        <%= f.email_field :email, class:"form-control", placeholder: "Input email" %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label sm-2">
        <%= f.label :password %>
      </div>
      <div class="sm-8">
        <%= f.password_field :password, class:"form-control", placeholder: "Input password" %>
      </div>
    </div> 

    <br>
    <div class="form-group">
      <div class="sm-10 offset-2">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update") %>
      </div>
    </div>
        
  <% end %>

  <%= link_to "Back to articles list", articles_path %>

  </div>
</div>

app/views/users/edit.html.erb
<br>
<h1 align="left">Edit your Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<style>
    body{
        background-color: #eaeaea;
    }
</style>
<br>
<h1 align = "center">All blog users </h1>
<div align ="center">
    <%= will_paginate %>
    <% @users.each do |user| %>
        <ul class="listing" >
            <div class="row" >
                <div class = "well col-md-4 offset-md-4" >
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title" >
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                    <% if logged_in? and current_user.admin? %>
                        <li><%= link_to "Delete this user", user_path(user), method: :delete, 
                            data: { confirm: "Are you sure you want to delete this user and all their articles"} %></li>
                    <% end %>
                  <hr>
                </div>
            </div>
        </ul>
    <% end %>
</div>

app/views/users/new.html.erb
<br>
<h1 class="text-center mt-4">Signup for Alpha-Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
    <div class="col-md-4 offset-md-4 center">
    <%= gravatar_for @user, size: 150 %>
    </div>
</div>

<h4 align="center"><%= @user.username %>'s articles </h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>